# .goreleaser.yaml
# Run: goreleaser release --snapshot --clean
version: 2

project_name: vmterminal

before:
  hooks:
    - go mod tidy

builds:
  # Linux builds (no CGO needed)
  - id: linux
    binary: vmterminal
    main: ./cmd/vmterminal
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/javanstorm/vmterminal/internal/version.Version={{.Version}}
      - -X github.com/javanstorm/vmterminal/internal/version.Commit={{.Commit}}
      - -X github.com/javanstorm/vmterminal/internal/version.BuildDate={{.Date}}
    flags:
      - -trimpath

  # macOS builds (require CGO for Virtualization.framework)
  # Note: Cross-compilation requires building on macOS
  - id: darwin
    binary: vmterminal
    main: ./cmd/vmterminal
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/javanstorm/vmterminal/internal/version.Version={{.Version}}
      - -X github.com/javanstorm/vmterminal/internal/version.Commit={{.Commit}}
      - -X github.com/javanstorm/vmterminal/internal/version.BuildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: javanstorm
    name: vmterminal
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
